export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CART_RESET = "CART_RESET";


// export const EDIT_QUANTITY_PRODUCT = 'EDIT_QUANTITY_PRODUCT';
// export const EDIT_QUANTITY_PRODUCT_SUCCESS = "EDIT_QUANTITY_PRODUCT_SUCCESS";
// export const EDIT_QUANTITY_PRODUCT_FAILED = "EDIT_QUANTITY_PRODUCT_FAILED";